# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OneDrive\Programador InXource\InXource\UI\FrmAgregarEvento.ui'
#
# Created: Mon Sep 19 10:13:36 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FrmAgregarEvento(object):
    def setupUi(self, FrmAgregarEvento):
        FrmAgregarEvento.setObjectName("FrmAgregarEvento")
        FrmAgregarEvento.setWindowModality(QtCore.Qt.NonModal)
        FrmAgregarEvento.resize(451, 702)
        FrmAgregarEvento.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox = QtGui.QGroupBox(FrmAgregarEvento)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 431, 321))
        self.groupBox.setObjectName("groupBox")
        self.RdbAnd = QtGui.QRadioButton(self.groupBox)
        self.RdbAnd.setGeometry(QtCore.QRect(210, 20, 82, 17))
        self.RdbAnd.setObjectName("RdbAnd")
        self.RdbOr = QtGui.QRadioButton(self.groupBox)
        self.RdbOr.setGeometry(QtCore.QRect(210, 40, 82, 17))
        self.RdbOr.setObjectName("RdbOr")
        self.CboListaEntradas = QtGui.QComboBox(self.groupBox)
        self.CboListaEntradas.setGeometry(QtCore.QRect(10, 40, 131, 22))
        self.CboListaEntradas.setObjectName("CboListaEntradas")
        self.TxtValorCondicion = QtGui.QLineEdit(self.groupBox)
        self.TxtValorCondicion.setGeometry(QtCore.QRect(150, 40, 41, 20))
        self.TxtValorCondicion.setObjectName("TxtValorCondicion")
        self.SpnValorCondicion = QtGui.QSpinBox(self.groupBox)
        self.SpnValorCondicion.setGeometry(QtCore.QRect(150, 40, 42, 22))
        self.SpnValorCondicion.setSingleStep(1)
        self.SpnValorCondicion.setProperty("value", 25)
        self.SpnValorCondicion.setObjectName("SpnValorCondicion")
        self.CboValorCondicion = QtGui.QComboBox(self.groupBox)
        self.CboValorCondicion.setGeometry(QtCore.QRect(150, 40, 41, 22))
        self.CboValorCondicion.setObjectName("CboValorCondicion")
        self.Condiciones = QtGui.QLabel(self.groupBox)
        self.Condiciones.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.Condiciones.setObjectName("Condiciones")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(150, 20, 46, 13))
        self.label.setObjectName("label")
        self.BtnAgregarCondicion = QtGui.QPushButton(self.groupBox)
        self.BtnAgregarCondicion.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.BtnAgregarCondicion.setObjectName("BtnAgregarCondicion")
        self.LstCondiciones = QtGui.QListWidget(self.groupBox)
        self.LstCondiciones.setGeometry(QtCore.QRect(10, 81, 411, 211))
        self.LstCondiciones.setObjectName("LstCondiciones")
        self.RdbNone = QtGui.QRadioButton(self.groupBox)
        self.RdbNone.setGeometry(QtCore.QRect(210, 60, 51, 17))
        self.RdbNone.setObjectName("RdbNone")
        self.groupBox_2 = QtGui.QGroupBox(FrmAgregarEvento)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 370, 421, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.CboListaSalidas = QtGui.QComboBox(self.groupBox_2)
        self.CboListaSalidas.setGeometry(QtCore.QRect(10, 40, 131, 22))
        self.CboListaSalidas.setObjectName("CboListaSalidas")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_2.setObjectName("label_2")
        self.CboValor = QtGui.QComboBox(self.groupBox_2)
        self.CboValor.setGeometry(QtCore.QRect(150, 40, 41, 22))
        self.CboValor.setObjectName("CboValor")
        self.BtnAgregarAccion = QtGui.QPushButton(self.groupBox_2)
        self.BtnAgregarAccion.setGeometry(QtCore.QRect(320, 40, 75, 23))
        self.BtnAgregarAccion.setObjectName("BtnAgregarAccion")
        self.LstAcciones = QtGui.QListWidget(self.groupBox_2)
        self.LstAcciones.setGeometry(QtCore.QRect(10, 80, 411, 191))
        self.LstAcciones.setObjectName("LstAcciones")
        self.BtnFormatLCD = QtGui.QPushButton(self.groupBox_2)
        self.BtnFormatLCD.setGeometry(QtCore.QRect(224, 40, 91, 23))
        self.BtnFormatLCD.setObjectName("BtnFormatLCD")
        self.BtnGuardar = QtGui.QPushButton(FrmAgregarEvento)
        self.BtnGuardar.setGeometry(QtCore.QRect(330, 670, 101, 23))
        self.BtnGuardar.setObjectName("BtnGuardar")
        self.BtnCerrar = QtGui.QPushButton(FrmAgregarEvento)
        self.BtnCerrar.setGeometry(QtCore.QRect(240, 670, 75, 23))
        self.BtnCerrar.setObjectName("BtnCerrar")
        self.TxtNombreEvento = QtGui.QLineEdit(FrmAgregarEvento)
        self.TxtNombreEvento.setGeometry(QtCore.QRect(130, 20, 151, 20))
        self.TxtNombreEvento.setObjectName("TxtNombreEvento")
        self.label_3 = QtGui.QLabel(FrmAgregarEvento)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(FrmAgregarEvento)
        QtCore.QMetaObject.connectSlotsByName(FrmAgregarEvento)

    def retranslateUi(self, FrmAgregarEvento):
        FrmAgregarEvento.setWindowTitle(QtGui.QApplication.translate("FrmAgregarEvento", "Agregar Evento", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FrmAgregarEvento", "Progrmacion de Condiciones", None, QtGui.QApplication.UnicodeUTF8))
        self.RdbAnd.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Y (AND)", None, QtGui.QApplication.UnicodeUTF8))
        self.RdbOr.setText(QtGui.QApplication.translate("FrmAgregarEvento", "O (OR)", None, QtGui.QApplication.UnicodeUTF8))
        self.Condiciones.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Condiciones", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Valor", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnAgregarCondicion.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.RdbNone.setText(QtGui.QApplication.translate("FrmAgregarEvento", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FrmAgregarEvento", "Programacion De Acciones", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Acciones", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnAgregarAccion.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnFormatLCD.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Formatear LCD", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnGuardar.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Guardar y Cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnCerrar.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Nombre Del Evento", None, QtGui.QApplication.UnicodeUTF8))

