# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OneDrive\Programador InXource\InXource\UI\FrmAgregarEvento.ui'
#
# Created: Mon Sep 12 10:22:43 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FrmAgregarEvento(object):
    def setupUi(self, FrmAgregarEvento):
        FrmAgregarEvento.setObjectName("FrmAgregarEvento")
        FrmAgregarEvento.setWindowModality(QtCore.Qt.NonModal)
        FrmAgregarEvento.resize(451, 703)
        FrmAgregarEvento.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox = QtGui.QGroupBox(FrmAgregarEvento)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 301))
        self.groupBox.setObjectName("groupBox")
        self.RdbAnd = QtGui.QRadioButton(self.groupBox)
        self.RdbAnd.setGeometry(QtCore.QRect(330, 50, 82, 17))
        self.RdbAnd.setObjectName("RdbAnd")
        self.RdbOr = QtGui.QRadioButton(self.groupBox)
        self.RdbOr.setGeometry(QtCore.QRect(330, 70, 82, 17))
        self.RdbOr.setObjectName("RdbOr")
        self.CboListaCondiciones = QtGui.QComboBox(self.groupBox)
        self.CboListaCondiciones.setGeometry(QtCore.QRect(10, 40, 131, 22))
        self.CboListaCondiciones.setObjectName("CboListaCondiciones")
        self.TxtValorCondicion = QtGui.QLineEdit(self.groupBox)
        self.TxtValorCondicion.setGeometry(QtCore.QRect(150, 40, 41, 20))
        self.TxtValorCondicion.setObjectName("TxtValorCondicion")
        self.SpnValorCondicion = QtGui.QSpinBox(self.groupBox)
        self.SpnValorCondicion.setGeometry(QtCore.QRect(150, 40, 42, 22))
        self.SpnValorCondicion.setSingleStep(1)
        self.SpnValorCondicion.setProperty("value", 25)
        self.SpnValorCondicion.setObjectName("SpnValorCondicion")
        self.CboValorCondicion = QtGui.QComboBox(self.groupBox)
        self.CboValorCondicion.setGeometry(QtCore.QRect(150, 40, 41, 22))
        self.CboValorCondicion.setObjectName("CboValorCondicion")
        self.Condiciones = QtGui.QLabel(self.groupBox)
        self.Condiciones.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.Condiciones.setObjectName("Condiciones")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(150, 20, 46, 13))
        self.label.setObjectName("label")
        self.LstCondiciones = QtGui.QListView(self.groupBox)
        self.LstCondiciones.setGeometry(QtCore.QRect(10, 100, 411, 181))
        self.LstCondiciones.setObjectName("LstCondiciones")
        self.BtnAgregarCondicion = QtGui.QPushButton(self.groupBox)
        self.BtnAgregarCondicion.setGeometry(QtCore.QRect(330, 20, 75, 23))
        self.BtnAgregarCondicion.setObjectName("BtnAgregarCondicion")
        self.groupBox_2 = QtGui.QGroupBox(FrmAgregarEvento)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 320, 421, 331))
        self.groupBox_2.setObjectName("groupBox_2")
        self.CboListaEventos = QtGui.QComboBox(self.groupBox_2)
        self.CboListaEventos.setGeometry(QtCore.QRect(10, 40, 131, 22))
        self.CboListaEventos.setObjectName("CboListaEventos")
        self.TxtLCDMessage = QtGui.QLineEdit(self.groupBox_2)
        self.TxtLCDMessage.setGeometry(QtCore.QRect(200, 40, 111, 20))
        self.TxtLCDMessage.setAutoFillBackground(False)
        self.TxtLCDMessage.setObjectName("TxtLCDMessage")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_2.setObjectName("label_2")
        self.LstEventos = QtGui.QListView(self.groupBox_2)
        self.LstEventos.setGeometry(QtCore.QRect(10, 80, 401, 231))
        self.LstEventos.setObjectName("LstEventos")
        self.CboValor = QtGui.QComboBox(self.groupBox_2)
        self.CboValor.setGeometry(QtCore.QRect(150, 40, 41, 22))
        self.CboValor.setObjectName("CboValor")
        self.BtnAgregarEvento = QtGui.QPushButton(self.groupBox_2)
        self.BtnAgregarEvento.setGeometry(QtCore.QRect(320, 40, 75, 23))
        self.BtnAgregarEvento.setObjectName("BtnAgregarEvento")
        self.BtnGuardar = QtGui.QPushButton(FrmAgregarEvento)
        self.BtnGuardar.setGeometry(QtCore.QRect(320, 670, 101, 23))
        self.BtnGuardar.setObjectName("BtnGuardar")
        self.BtnCerrar = QtGui.QPushButton(FrmAgregarEvento)
        self.BtnCerrar.setGeometry(QtCore.QRect(230, 670, 75, 23))
        self.BtnCerrar.setObjectName("BtnCerrar")

        self.retranslateUi(FrmAgregarEvento)
        QtCore.QMetaObject.connectSlotsByName(FrmAgregarEvento)

    def retranslateUi(self, FrmAgregarEvento):
        FrmAgregarEvento.setWindowTitle(QtGui.QApplication.translate("FrmAgregarEvento", "Agregar Evento", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FrmAgregarEvento", "Condiciones", None, QtGui.QApplication.UnicodeUTF8))
        self.RdbAnd.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Y (AND)", None, QtGui.QApplication.UnicodeUTF8))
        self.RdbOr.setText(QtGui.QApplication.translate("FrmAgregarEvento", "O (OR)", None, QtGui.QApplication.UnicodeUTF8))
        self.Condiciones.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Condiciones", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Valor", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnAgregarCondicion.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FrmAgregarEvento", "Eventos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Condiciones", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnAgregarEvento.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnGuardar.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Guardar y Cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnCerrar.setText(QtGui.QApplication.translate("FrmAgregarEvento", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))

